# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapiapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='lacation',
            new_name='location',
        ),
    ]
